#!/usr/bin/env bash
# install the ufw firewall and set up rules on web-01

sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
allow ufw allow 22/tcp
sudo ufw enable
sudo ufw status
